
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}" #optional
mixins=["mixins.adjcore.json"]

# The description text for the mod (multi line!) )
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="attributeslib"
mandatory=true
versionRange="[${attributeslib_version},)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="curios"
mandatory=true
versionRange="[${curios_version},)"
ordering="AFTER"
side="BOTH"